-- Add Property OS-specific security event types
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'PROPERTY_OS_ANALYSIS_REQUEST';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'PROPERTY_OS_ANALYSIS_SUCCESS';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'PROPERTY_OS_ANALYSIS_FAILURE';
