/* tslint:disable */
/* eslint-disable */
/**
 * Model Integrity Layer (MIL) API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AttestationKeySet {
    'keys': Array<AttestationPublicKey>;
}
export interface AttestationPublicKey {
    'kid': string;
    'alg': AttestationPublicKeyAlgEnum;
    'public_key_base64': string;
    'created_at': string;
    'retired_at'?: string | null;
}

export const AttestationPublicKeyAlgEnum = {
    Ed25519: 'Ed25519'
} as const;

export type AttestationPublicKeyAlgEnum = typeof AttestationPublicKeyAlgEnum[keyof typeof AttestationPublicKeyAlgEnum];

export interface ErrorResponse {
    'error': string;
    'message': string;
    'details'?: { [key: string]: any; };
}
export interface GenericOk {
    'ok': boolean;
}
export interface LineageStepSummary {
    'step_seq': number;
    'step_type': string;
    'step_hash': string;
    'prev_step_hash': string;
    'payload_digest': string;
    'enc_version': number;
}
export interface LineageSummary {
    'chain_id': string;
    'tenant_id': string;
    'record_hash': string;
    'prev_hash': string;
    'trace_root_hash': string;
    'trace_steps': number;
}
export interface LineageVerifyAttestation {
    'schema': string;
    'as_of': string;
    'tenant_id': string;
    'chain_id': string;
    'from_hash': string;
    'to_hash': string;
    'chain_valid': boolean;
    'records_verified': number;
    'break_detected': boolean;
    'first_invalid_hash': string | null;
    'server_nonce': string;
}
export interface MilEvaluateRequest {
    'tenant_id': string;
    'target_id': string;
    'mode': MilEvaluateRequestModeEnum;
    'request_id': string;
    'payload': { [key: string]: any; };
}

export const MilEvaluateRequestModeEnum = {
    SyncHttp: 'sync_http',
    AsyncJob: 'async_job'
} as const;

export type MilEvaluateRequestModeEnum = typeof MilEvaluateRequestModeEnum[keyof typeof MilEvaluateRequestModeEnum];

export interface MilEvaluateResponse {
    'status': MilEvaluateResponseStatusEnum;
    'evaluation_id': string;
    'result'?: { [key: string]: any; };
    'lineage'?: LineageSummary;
}

export const MilEvaluateResponseStatusEnum = {
    Completed: 'COMPLETED',
    Queued: 'QUEUED'
} as const;

export type MilEvaluateResponseStatusEnum = typeof MilEvaluateResponseStatusEnum[keyof typeof MilEvaluateResponseStatusEnum];

export interface MilEvaluationStatusResponse {
    'status': MilEvaluationStatusResponseStatusEnum;
    'tenant_state': MilEvaluationStatusResponseTenantStateEnum;
    'evaluation_id': string;
    'result'?: { [key: string]: any; };
    'lineage'?: LineageSummary;
    'error'?: ErrorResponse;
}

export const MilEvaluationStatusResponseStatusEnum = {
    Queued: 'QUEUED',
    Running: 'RUNNING',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    Blocked: 'BLOCKED'
} as const;

export type MilEvaluationStatusResponseStatusEnum = typeof MilEvaluationStatusResponseStatusEnum[keyof typeof MilEvaluationStatusResponseStatusEnum];
export const MilEvaluationStatusResponseTenantStateEnum = {
    Active: 'ACTIVE',
    RekeyRequired: 'REKEY_REQUIRED',
    RekeyOverdue: 'REKEY_OVERDUE',
    RekeyingMaintenance: 'REKEYING_MAINTENANCE',
    CryptoDeleted: 'CRYPTO_DELETED'
} as const;

export type MilEvaluationStatusResponseTenantStateEnum = typeof MilEvaluationStatusResponseTenantStateEnum[keyof typeof MilEvaluationStatusResponseTenantStateEnum];

export interface MilLineageEvaluationResponse {
    'tenant_id': string;
    'evaluation_id': string;
    'record_hash': string;
    'prev_hash': string;
    'trace_root_hash': string;
    'trace_steps': number;
    'steps': Array<LineageStepSummary>;
}
export interface MilLineageVerifyRequest {
    'tenant_id': string;
    'from_hash': string;
    'to_hash': string;
}
export interface MilLineageVerifyResponse {
    'result': LineageVerifyAttestation;
    'signature': SignatureEnvelope;
}
export interface RekeyJobResponse {
    'tenant_id': string;
    'job_id': string;
    'status': RekeyJobResponseStatusEnum;
    'old_kms_key_id'?: string | null;
    'new_kms_key_id'?: string | null;
    'result_summary'?: { [key: string]: any; } | null;
}

export const RekeyJobResponseStatusEnum = {
    Scheduled: 'SCHEDULED',
    Ready: 'READY',
    Running: 'RUNNING',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    Aborted: 'ABORTED'
} as const;

export type RekeyJobResponseStatusEnum = typeof RekeyJobResponseStatusEnum[keyof typeof RekeyJobResponseStatusEnum];

export interface RekeyRunRequest {
    'job_id': string;
    'new_kms_key_id': string;
}
export interface RekeyScheduleRequest {
    'trigger_type': RekeyScheduleRequestTriggerTypeEnum;
    'scheduled_start': string;
    'scheduled_end'?: string | null;
    'reason'?: string | null;
}

export const RekeyScheduleRequestTriggerTypeEnum = {
    KeyAgeThreshold: 'KEY_AGE_THRESHOLD',
    CryptoPolicyUpdate: 'CRYPTO_POLICY_UPDATE',
    SecurityIncidentResponse: 'SECURITY_INCIDENT_RESPONSE',
    TenantRequested: 'TENANT_REQUESTED'
} as const;

export type RekeyScheduleRequestTriggerTypeEnum = typeof RekeyScheduleRequestTriggerTypeEnum[keyof typeof RekeyScheduleRequestTriggerTypeEnum];

export interface SignatureEnvelope {
    'alg': SignatureEnvelopeAlgEnum;
    'kid': string;
    'sig': string;
}

export const SignatureEnvelopeAlgEnum = {
    Ed25519: 'Ed25519'
} as const;

export type SignatureEnvelopeAlgEnum = typeof SignatureEnvelopeAlgEnum[keyof typeof SignatureEnvelopeAlgEnum];

export interface TenantCryptoStatusResponse {
    'tenant_id': string;
    'state': TenantCryptoStatusResponseStateEnum;
    'kms_key_id': string;
    'rekey_deadline'?: string | null;
}

export const TenantCryptoStatusResponseStateEnum = {
    Active: 'ACTIVE',
    RekeyRequired: 'REKEY_REQUIRED',
    RekeyOverdue: 'REKEY_OVERDUE',
    RekeyingMaintenance: 'REKEYING_MAINTENANCE',
    CryptoDeleted: 'CRYPTO_DELETED'
} as const;

export type TenantCryptoStatusResponseStateEnum = typeof TenantCryptoStatusResponseStateEnum[keyof typeof TenantCryptoStatusResponseStateEnum];


/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get evaluation status/result
         * @param {string} evaluationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milEvaluateEvaluationIdGet: async (evaluationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'evaluationId' is not null or undefined
            assertParamExists('milEvaluateEvaluationIdGet', 'evaluationId', evaluationId)
            const localVarPath = `/mil/evaluate/{evaluation_id}`
                .replace(`{${"evaluation_id"}}`, encodeURIComponent(String(evaluationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Evaluate a model target with MIL governance (sync or async)
         * @param {MilEvaluateRequest} milEvaluateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milEvaluatePost: async (milEvaluateRequest: MilEvaluateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'milEvaluateRequest' is not null or undefined
            assertParamExists('milEvaluatePost', 'milEvaluateRequest', milEvaluateRequest)
            const localVarPath = `/mil/evaluate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(milEvaluateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get lineage hashes/digests for an evaluation (no decryption)
         * @param {string} evaluationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milLineageEvaluationEvaluationIdGet: async (evaluationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'evaluationId' is not null or undefined
            assertParamExists('milLineageEvaluationEvaluationIdGet', 'evaluationId', evaluationId)
            const localVarPath = `/mil/lineage/evaluation/{evaluation_id}`
                .replace(`{${"evaluation_id"}}`, encodeURIComponent(String(evaluationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Verify chain continuity for a tenant and return signed attestation (allowed when overdue)
         * @param {MilLineageVerifyRequest} milLineageVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milLineageVerifyPost: async (milLineageVerifyRequest: MilLineageVerifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'milLineageVerifyRequest' is not null or undefined
            assertParamExists('milLineageVerifyPost', 'milLineageVerifyRequest', milLineageVerifyRequest)
            const localVarPath = `/mil/lineage/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(milLineageVerifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Crypto-delete tenant payload key (payloads unrecoverable; hash continuity preserved)
         * @param {string} tenantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milTenantTenantIdCryptoDeletePost: async (tenantId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('milTenantTenantIdCryptoDeletePost', 'tenantId', tenantId)
            const localVarPath = `/mil/tenant/{tenant_id}/crypto-delete`
                .replace(`{${"tenant_id"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get tenant crypto governance status
         * @param {string} tenantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milTenantTenantIdCryptoStatusGet: async (tenantId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('milTenantTenantIdCryptoStatusGet', 'tenantId', tenantId)
            const localVarPath = `/mil/tenant/{tenant_id}/crypto-status`
                .replace(`{${"tenant_id"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Run re-key job (maintenance freeze; everything pauses)
         * @param {string} tenantId 
         * @param {RekeyRunRequest} rekeyRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milTenantTenantIdRekeyRunPost: async (tenantId: string, rekeyRunRequest: RekeyRunRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('milTenantTenantIdRekeyRunPost', 'tenantId', tenantId)
            // verify required parameter 'rekeyRunRequest' is not null or undefined
            assertParamExists('milTenantTenantIdRekeyRunPost', 'rekeyRunRequest', rekeyRunRequest)
            const localVarPath = `/mil/tenant/{tenant_id}/rekey/run`
                .replace(`{${"tenant_id"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rekeyRunRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Schedule a tenant re-key maintenance job
         * @param {string} tenantId 
         * @param {RekeyScheduleRequest} rekeyScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milTenantTenantIdRekeySchedulePost: async (tenantId: string, rekeyScheduleRequest: RekeyScheduleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('milTenantTenantIdRekeySchedulePost', 'tenantId', tenantId)
            // verify required parameter 'rekeyScheduleRequest' is not null or undefined
            assertParamExists('milTenantTenantIdRekeySchedulePost', 'rekeyScheduleRequest', rekeyScheduleRequest)
            const localVarPath = `/mil/tenant/{tenant_id}/rekey/schedule`
                .replace(`{${"tenant_id"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rekeyScheduleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Public keys for verifying MIL attestations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wellKnownMilAttestationKeysJsonGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/.well-known/mil-attestation-keys.json`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get evaluation status/result
         * @param {string} evaluationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async milEvaluateEvaluationIdGet(evaluationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MilEvaluationStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.milEvaluateEvaluationIdGet(evaluationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.milEvaluateEvaluationIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Evaluate a model target with MIL governance (sync or async)
         * @param {MilEvaluateRequest} milEvaluateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async milEvaluatePost(milEvaluateRequest: MilEvaluateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MilEvaluateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.milEvaluatePost(milEvaluateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.milEvaluatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get lineage hashes/digests for an evaluation (no decryption)
         * @param {string} evaluationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async milLineageEvaluationEvaluationIdGet(evaluationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MilLineageEvaluationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.milLineageEvaluationEvaluationIdGet(evaluationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.milLineageEvaluationEvaluationIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Verify chain continuity for a tenant and return signed attestation (allowed when overdue)
         * @param {MilLineageVerifyRequest} milLineageVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async milLineageVerifyPost(milLineageVerifyRequest: MilLineageVerifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MilLineageVerifyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.milLineageVerifyPost(milLineageVerifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.milLineageVerifyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Crypto-delete tenant payload key (payloads unrecoverable; hash continuity preserved)
         * @param {string} tenantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async milTenantTenantIdCryptoDeletePost(tenantId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericOk>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.milTenantTenantIdCryptoDeletePost(tenantId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.milTenantTenantIdCryptoDeletePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get tenant crypto governance status
         * @param {string} tenantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async milTenantTenantIdCryptoStatusGet(tenantId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TenantCryptoStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.milTenantTenantIdCryptoStatusGet(tenantId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.milTenantTenantIdCryptoStatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Run re-key job (maintenance freeze; everything pauses)
         * @param {string} tenantId 
         * @param {RekeyRunRequest} rekeyRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async milTenantTenantIdRekeyRunPost(tenantId: string, rekeyRunRequest: RekeyRunRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RekeyJobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.milTenantTenantIdRekeyRunPost(tenantId, rekeyRunRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.milTenantTenantIdRekeyRunPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Schedule a tenant re-key maintenance job
         * @param {string} tenantId 
         * @param {RekeyScheduleRequest} rekeyScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async milTenantTenantIdRekeySchedulePost(tenantId: string, rekeyScheduleRequest: RekeyScheduleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RekeyJobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.milTenantTenantIdRekeySchedulePost(tenantId, rekeyScheduleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.milTenantTenantIdRekeySchedulePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Public keys for verifying MIL attestations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async wellKnownMilAttestationKeysJsonGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttestationKeySet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.wellKnownMilAttestationKeysJsonGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.wellKnownMilAttestationKeysJsonGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Get evaluation status/result
         * @param {string} evaluationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milEvaluateEvaluationIdGet(evaluationId: string, options?: RawAxiosRequestConfig): AxiosPromise<MilEvaluationStatusResponse> {
            return localVarFp.milEvaluateEvaluationIdGet(evaluationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Evaluate a model target with MIL governance (sync or async)
         * @param {MilEvaluateRequest} milEvaluateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milEvaluatePost(milEvaluateRequest: MilEvaluateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MilEvaluateResponse> {
            return localVarFp.milEvaluatePost(milEvaluateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get lineage hashes/digests for an evaluation (no decryption)
         * @param {string} evaluationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milLineageEvaluationEvaluationIdGet(evaluationId: string, options?: RawAxiosRequestConfig): AxiosPromise<MilLineageEvaluationResponse> {
            return localVarFp.milLineageEvaluationEvaluationIdGet(evaluationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Verify chain continuity for a tenant and return signed attestation (allowed when overdue)
         * @param {MilLineageVerifyRequest} milLineageVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milLineageVerifyPost(milLineageVerifyRequest: MilLineageVerifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<MilLineageVerifyResponse> {
            return localVarFp.milLineageVerifyPost(milLineageVerifyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Crypto-delete tenant payload key (payloads unrecoverable; hash continuity preserved)
         * @param {string} tenantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milTenantTenantIdCryptoDeletePost(tenantId: string, options?: RawAxiosRequestConfig): AxiosPromise<GenericOk> {
            return localVarFp.milTenantTenantIdCryptoDeletePost(tenantId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get tenant crypto governance status
         * @param {string} tenantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milTenantTenantIdCryptoStatusGet(tenantId: string, options?: RawAxiosRequestConfig): AxiosPromise<TenantCryptoStatusResponse> {
            return localVarFp.milTenantTenantIdCryptoStatusGet(tenantId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Run re-key job (maintenance freeze; everything pauses)
         * @param {string} tenantId 
         * @param {RekeyRunRequest} rekeyRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milTenantTenantIdRekeyRunPost(tenantId: string, rekeyRunRequest: RekeyRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<RekeyJobResponse> {
            return localVarFp.milTenantTenantIdRekeyRunPost(tenantId, rekeyRunRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Schedule a tenant re-key maintenance job
         * @param {string} tenantId 
         * @param {RekeyScheduleRequest} rekeyScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        milTenantTenantIdRekeySchedulePost(tenantId: string, rekeyScheduleRequest: RekeyScheduleRequest, options?: RawAxiosRequestConfig): AxiosPromise<RekeyJobResponse> {
            return localVarFp.milTenantTenantIdRekeySchedulePost(tenantId, rekeyScheduleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Public keys for verifying MIL attestations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        wellKnownMilAttestationKeysJsonGet(options?: RawAxiosRequestConfig): AxiosPromise<AttestationKeySet> {
            return localVarFp.wellKnownMilAttestationKeysJsonGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Get evaluation status/result
     * @param {string} evaluationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public milEvaluateEvaluationIdGet(evaluationId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).milEvaluateEvaluationIdGet(evaluationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Evaluate a model target with MIL governance (sync or async)
     * @param {MilEvaluateRequest} milEvaluateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public milEvaluatePost(milEvaluateRequest: MilEvaluateRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).milEvaluatePost(milEvaluateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get lineage hashes/digests for an evaluation (no decryption)
     * @param {string} evaluationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public milLineageEvaluationEvaluationIdGet(evaluationId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).milLineageEvaluationEvaluationIdGet(evaluationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Verify chain continuity for a tenant and return signed attestation (allowed when overdue)
     * @param {MilLineageVerifyRequest} milLineageVerifyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public milLineageVerifyPost(milLineageVerifyRequest: MilLineageVerifyRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).milLineageVerifyPost(milLineageVerifyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Crypto-delete tenant payload key (payloads unrecoverable; hash continuity preserved)
     * @param {string} tenantId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public milTenantTenantIdCryptoDeletePost(tenantId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).milTenantTenantIdCryptoDeletePost(tenantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get tenant crypto governance status
     * @param {string} tenantId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public milTenantTenantIdCryptoStatusGet(tenantId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).milTenantTenantIdCryptoStatusGet(tenantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Run re-key job (maintenance freeze; everything pauses)
     * @param {string} tenantId 
     * @param {RekeyRunRequest} rekeyRunRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public milTenantTenantIdRekeyRunPost(tenantId: string, rekeyRunRequest: RekeyRunRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).milTenantTenantIdRekeyRunPost(tenantId, rekeyRunRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Schedule a tenant re-key maintenance job
     * @param {string} tenantId 
     * @param {RekeyScheduleRequest} rekeyScheduleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public milTenantTenantIdRekeySchedulePost(tenantId: string, rekeyScheduleRequest: RekeyScheduleRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).milTenantTenantIdRekeySchedulePost(tenantId, rekeyScheduleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Public keys for verifying MIL attestations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public wellKnownMilAttestationKeysJsonGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).wellKnownMilAttestationKeysJsonGet(options).then((request) => request(this.axios, this.basePath));
    }
}



