CREATE EXTENSION IF NOT EXISTS "pgcrypto";

ALTER TABLE "Property" ADD COLUMN "id_new" UUID NOT NULL DEFAULT gen_random_uuid();

ALTER TABLE "PropertyMarketingProfile" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "PropertyPhoto" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "PropertyAmenity" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "Unit" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "SyndicationQueue" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "SyndicationErrorLog" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "MaintenanceRequest" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "MaintenanceAsset" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "MaintenanceSlaPolicy" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "Document" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "RentalApplication" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "PropertyInquiry" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "Tour" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "LeadApplication" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "Expense" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "UnitInspection" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "RepairEstimate" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "ScheduleEvent" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "AgentRun" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "CommunicationLog" ADD COLUMN "propertyId_new" UUID;
ALTER TABLE "BankTransaction" ADD COLUMN "propertyId_new" UUID;

UPDATE "Property" SET "id_new" = gen_random_uuid() WHERE "id_new" IS NULL;

UPDATE "PropertyMarketingProfile" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "PropertyMarketingProfile"."propertyId" = p."id";
UPDATE "PropertyPhoto" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "PropertyPhoto"."propertyId" = p."id";
UPDATE "PropertyAmenity" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "PropertyAmenity"."propertyId" = p."id";
UPDATE "Unit" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "Unit"."propertyId" = p."id";
UPDATE "SyndicationQueue" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "SyndicationQueue"."propertyId" = p."id";
UPDATE "SyndicationErrorLog" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "SyndicationErrorLog"."propertyId" = p."id";
UPDATE "MaintenanceRequest" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "MaintenanceRequest"."propertyId" = p."id";
UPDATE "MaintenanceAsset" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "MaintenanceAsset"."propertyId" = p."id";
UPDATE "MaintenanceSlaPolicy" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "MaintenanceSlaPolicy"."propertyId" = p."id";
UPDATE "Document" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "Document"."propertyId" = p."id";
UPDATE "RentalApplication" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "RentalApplication"."propertyId" = p."id";
UPDATE "PropertyInquiry" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "PropertyInquiry"."propertyId" = p."id";
UPDATE "Tour" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "Tour"."propertyId" = p."id";
UPDATE "LeadApplication" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "LeadApplication"."propertyId" = p."id";
UPDATE "Expense" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "Expense"."propertyId" = p."id";
UPDATE "UnitInspection" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "UnitInspection"."propertyId" = p."id";
UPDATE "RepairEstimate" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "RepairEstimate"."propertyId" = p."id";
UPDATE "ScheduleEvent" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "ScheduleEvent"."propertyId" = p."id";
UPDATE "AgentRun" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "AgentRun"."propertyId" = p."id";
UPDATE "CommunicationLog" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "CommunicationLog"."propertyId" = p."id";
UPDATE "BankTransaction" SET "propertyId_new" = p."id_new" FROM "Property" p WHERE "BankTransaction"."propertyId" = p."id";

ALTER TABLE "PropertyMarketingProfile" DROP CONSTRAINT IF EXISTS "PropertyMarketingProfile_propertyId_fkey";
ALTER TABLE "PropertyPhoto" DROP CONSTRAINT IF EXISTS "PropertyPhoto_propertyId_fkey";
ALTER TABLE "PropertyAmenity" DROP CONSTRAINT IF EXISTS "PropertyAmenity_propertyId_fkey";
ALTER TABLE "Unit" DROP CONSTRAINT IF EXISTS "Unit_propertyId_fkey";
ALTER TABLE "SyndicationQueue" DROP CONSTRAINT IF EXISTS "SyndicationQueue_propertyId_fkey";
ALTER TABLE "SyndicationErrorLog" DROP CONSTRAINT IF EXISTS "SyndicationErrorLog_propertyId_fkey";
ALTER TABLE "MaintenanceRequest" DROP CONSTRAINT IF EXISTS "MaintenanceRequest_propertyId_fkey";
ALTER TABLE "MaintenanceAsset" DROP CONSTRAINT IF EXISTS "MaintenanceAsset_propertyId_fkey";
ALTER TABLE "MaintenanceSlaPolicy" DROP CONSTRAINT IF EXISTS "MaintenanceSlaPolicy_propertyId_fkey";
ALTER TABLE "Document" DROP CONSTRAINT IF EXISTS "Document_propertyId_fkey";
ALTER TABLE "RentalApplication" DROP CONSTRAINT IF EXISTS "RentalApplication_propertyId_fkey";
ALTER TABLE "PropertyInquiry" DROP CONSTRAINT IF EXISTS "PropertyInquiry_propertyId_fkey";
ALTER TABLE "Tour" DROP CONSTRAINT IF EXISTS "Tour_propertyId_fkey";
ALTER TABLE "LeadApplication" DROP CONSTRAINT IF EXISTS "LeadApplication_propertyId_fkey";
ALTER TABLE "Expense" DROP CONSTRAINT IF EXISTS "Expense_propertyId_fkey";
ALTER TABLE "UnitInspection" DROP CONSTRAINT IF EXISTS "UnitInspection_propertyId_fkey";
ALTER TABLE "RepairEstimate" DROP CONSTRAINT IF EXISTS "RepairEstimate_propertyId_fkey";
ALTER TABLE "ScheduleEvent" DROP CONSTRAINT IF EXISTS "ScheduleEvent_propertyId_fkey";
ALTER TABLE "AgentRun" DROP CONSTRAINT IF EXISTS "AgentRun_propertyId_fkey";
ALTER TABLE "CommunicationLog" DROP CONSTRAINT IF EXISTS "CommunicationLog_propertyId_fkey";
ALTER TABLE "BankTransaction" DROP CONSTRAINT IF EXISTS "BankTransaction_propertyId_fkey";

ALTER TABLE "PropertyMarketingProfile" DROP COLUMN "propertyId";
ALTER TABLE "PropertyPhoto" DROP COLUMN "propertyId";
ALTER TABLE "PropertyAmenity" DROP COLUMN "propertyId";
ALTER TABLE "Unit" DROP COLUMN "propertyId";
ALTER TABLE "SyndicationQueue" DROP COLUMN "propertyId";
ALTER TABLE "SyndicationErrorLog" DROP COLUMN "propertyId";
ALTER TABLE "MaintenanceRequest" DROP COLUMN "propertyId";
ALTER TABLE "MaintenanceAsset" DROP COLUMN "propertyId";
ALTER TABLE "MaintenanceSlaPolicy" DROP COLUMN "propertyId";
ALTER TABLE "Document" DROP COLUMN "propertyId";
ALTER TABLE "RentalApplication" DROP COLUMN "propertyId";
ALTER TABLE "PropertyInquiry" DROP COLUMN "propertyId";
ALTER TABLE "Tour" DROP COLUMN "propertyId";
ALTER TABLE "LeadApplication" DROP COLUMN "propertyId";
ALTER TABLE "Expense" DROP COLUMN "propertyId";
ALTER TABLE "UnitInspection" DROP COLUMN "propertyId";
ALTER TABLE "RepairEstimate" DROP COLUMN "propertyId";
ALTER TABLE "ScheduleEvent" DROP COLUMN "propertyId";
ALTER TABLE "AgentRun" DROP COLUMN "propertyId";
ALTER TABLE "CommunicationLog" DROP COLUMN "propertyId";
ALTER TABLE "BankTransaction" DROP COLUMN "propertyId";

ALTER TABLE "PropertyMarketingProfile" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "PropertyPhoto" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "PropertyAmenity" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "Unit" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "SyndicationQueue" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "SyndicationErrorLog" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "MaintenanceRequest" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "MaintenanceAsset" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "MaintenanceSlaPolicy" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "Document" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "RentalApplication" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "PropertyInquiry" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "Tour" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "LeadApplication" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "Expense" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "UnitInspection" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "RepairEstimate" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "ScheduleEvent" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "AgentRun" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "CommunicationLog" RENAME COLUMN "propertyId_new" TO "propertyId";
ALTER TABLE "BankTransaction" RENAME COLUMN "propertyId_new" TO "propertyId";

ALTER TABLE "PropertyMarketingProfile" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "PropertyPhoto" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "PropertyAmenity" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "Unit" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "SyndicationQueue" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "SyndicationErrorLog" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "MaintenanceAsset" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "RentalApplication" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "PropertyInquiry" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "Tour" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "LeadApplication" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "Expense" ALTER COLUMN "propertyId" SET NOT NULL;
ALTER TABLE "UnitInspection" ALTER COLUMN "propertyId" SET NOT NULL;

ALTER TABLE "Property" DROP CONSTRAINT IF EXISTS "Property_pkey";
ALTER TABLE "Property" DROP COLUMN "id";
ALTER TABLE "Property" RENAME COLUMN "id_new" TO "id";
ALTER TABLE "Property" ADD CONSTRAINT "Property_pkey" PRIMARY KEY ("id");
ALTER TABLE "Property" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
DROP SEQUENCE IF EXISTS "Property_id_seq";

CREATE UNIQUE INDEX "PropertyMarketingProfile_propertyId_key" ON "PropertyMarketingProfile"("propertyId");
CREATE INDEX "PropertyPhoto_propertyId_idx" ON "PropertyPhoto"("propertyId");
CREATE UNIQUE INDEX "PropertyAmenity_propertyId_amenityId_key" ON "PropertyAmenity"("propertyId", "amenityId");
CREATE INDEX "PropertyAmenity_propertyId_idx" ON "PropertyAmenity"("propertyId");
CREATE INDEX "SyndicationQueue_propertyId_idx" ON "SyndicationQueue"("propertyId");
CREATE INDEX "SyndicationErrorLog_propertyId_idx" ON "SyndicationErrorLog"("propertyId");
CREATE UNIQUE INDEX "MaintenanceAsset_property_unit_name_key" ON "MaintenanceAsset"("propertyId", "unitId", "name");
CREATE INDEX "MaintenanceAsset_propertyId_idx" ON "MaintenanceAsset"("propertyId");
CREATE UNIQUE INDEX "MaintenanceSlaPolicy_property_priority_key" ON "MaintenanceSlaPolicy"("propertyId", "priority");
CREATE INDEX "Document_propertyId_idx" ON "Document"("propertyId");
CREATE INDEX "PropertyInquiry_propertyId_idx" ON "PropertyInquiry"("propertyId");
CREATE INDEX "Tour_propertyId_idx" ON "Tour"("propertyId");
CREATE INDEX "LeadApplication_propertyId_idx" ON "LeadApplication"("propertyId");
CREATE INDEX "UnitInspection_propertyId_idx" ON "UnitInspection"("propertyId");
CREATE INDEX "ScheduleEvent_propertyId_idx" ON "ScheduleEvent"("propertyId");
CREATE INDEX "AgentRun_propertyId_idx" ON "AgentRun"("propertyId");
CREATE INDEX "CommunicationLog_propertyId_createdAt_idx" ON "CommunicationLog"("propertyId", "createdAt");
CREATE INDEX "BankTransaction_propertyId_date_idx" ON "BankTransaction"("propertyId", "date");

ALTER TABLE "PropertyMarketingProfile" ADD CONSTRAINT "PropertyMarketingProfile_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PropertyPhoto" ADD CONSTRAINT "PropertyPhoto_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PropertyAmenity" ADD CONSTRAINT "PropertyAmenity_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Unit" ADD CONSTRAINT "Unit_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SyndicationQueue" ADD CONSTRAINT "SyndicationQueue_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SyndicationErrorLog" ADD CONSTRAINT "SyndicationErrorLog_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MaintenanceRequest" ADD CONSTRAINT "MaintenanceRequest_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MaintenanceAsset" ADD CONSTRAINT "MaintenanceAsset_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MaintenanceSlaPolicy" ADD CONSTRAINT "MaintenanceSlaPolicy_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Document" ADD CONSTRAINT "Document_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RentalApplication" ADD CONSTRAINT "RentalApplication_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PropertyInquiry" ADD CONSTRAINT "PropertyInquiry_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Tour" ADD CONSTRAINT "Tour_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LeadApplication" ADD CONSTRAINT "LeadApplication_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "UnitInspection" ADD CONSTRAINT "UnitInspection_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RepairEstimate" ADD CONSTRAINT "RepairEstimate_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ScheduleEvent" ADD CONSTRAINT "ScheduleEvent_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AgentRun" ADD CONSTRAINT "AgentRun_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CommunicationLog" ADD CONSTRAINT "CommunicationLog_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "BankTransaction" ADD CONSTRAINT "BankTransaction_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;
