-- AlterTable
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "unitNumber" TEXT;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "bedrooms" DOUBLE PRECISION;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "bathrooms" DOUBLE PRECISION;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "squareFeet" INTEGER;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "hasParking" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "hasLaundry" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "hasBalcony" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "hasAC" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "isFurnished" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "petsAllowed" BOOLEAN NOT NULL DEFAULT false;
